- name: Install the latest version of Apache and MariaDB
  package:
    name:
      - apache2
      - libapache2-mod-php
      - php-mysql
    state: latest

- name: Restart Apache
  service: name=apache2 state=restarted
